name: Dagger Workflow
on:
  workflow_dispatch:
jobs:
  Run_Dagger:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dagger
        run: |
          echo "Installing dagger"
          pip install dagger-io
          pip install anyio
          pip install dagger
      - name: Python Version
        run: |
          python --version
