name: Dagger Workflow
on:
    workflow_dispatch:
jobs:
  Run_Dagger:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    steps:
        - name: Install Dagger
          run: |
            echo "Installing dagger"
            pip install dagger-io
        - name: Run Dagger
          run: |
            dagger run python main.py
