name: Dagger Workflow
on:
  workflow_dispatch:
jobs:
  Run_Dagger:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install Dagger
        run: |
          echo "Installing dagger"
          curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
      - name: Run Dagger
        working-directory: /home/runner/work/dagger/ci
        run: |
          dagger run python main.py
