name: Dagger Workflow
on:
    workflow_dispatch:
jobs:
  Run_Dagger:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    steps:
        - name: Install Dagger
          run: |
            echo "Installing dagger"
            pip install dagger-io
        - name: Add Dagger to PATH
          run: echo "::add-path::$(python -m site --user-base)/bin"
        - name: Verify Dagger Installation
          run: dagger --version
        - name: Run Dagger
          run: |
            dagger run python ci/main.py
