name: Dagger Workflow
on:
    workflow_dispatch:
jobs:
  Run_Dagger:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    steps:
        - name: Install Dagger
          working-directory: .
          run: |
            echo "Installing python3.9"
            sudo apt-get install python3.9
            echo "Installing dagger"
            sudo pip install dagger-io
        - name: Run Dagger
          run: |
            dagger run python ci/main.py
