name: Dagger Workflow
on:
    workflow_dispatch:
jobs:
  Run_Dagger:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    steps:
        - name: Install Dagger
          working-directory: .
          run: |
            sudo apt-get install python3.9
            sudo pip install dagger-io
