name: Dagger Workflow
on:
  workflow_dispatch:
jobs:
  Run_Dagger:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python 2.x
        run: |
          sudo apt update
          sudo apt install python2
      - name: Install Dagger CLI
        run: |
          echo "Installing Dagger CLI"
          curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
      - name: Install Dagger
        run: |
          echo "Installing Dagger library"
          pip install dagger-io
          pip install anyio
          pip install dagger
      - name: Python Version
        run: |
          python2 --version
      - name: Run Dagger
        working-directory: ci
        run: |
          dagger run python2 main.py
