name: Dagger Workflow
on:
  workflow_dispatch:
jobs:
  Run_Dagger:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install Dagger
        run: |
          echo "Installing dagger"
          pip install dagger-io

      - name: Set PATH
        run: |
          echo "PATH=$PATH:$(python -m site --user-base)/bin" >> $GITHUB_ENV

      - name: Run Dagger
        run: |
          dagger run python ci/main.py
